name: Auto Update IPTV

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd generators/zee5 && npm install
          cd ../jiotv && npm install
          cd ../sonyliv && npm install

      - run: |
          node generators/zee5/index.js
          node generators/jiotv/index.js
          node generators/sonyliv/index.js
          node generators/index-builder/index.js

      - run: |
          git config user.name "iptv-bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Auto update playlists" || exit 0
          git push
